# Generated by Django 3.1.6 on 2021-02-10 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paon', models.CharField(max_length=80)),
                ('saon', models.CharField(blank=True, default='', max_length=80)),
                ('street', models.CharField(max_length=80)),
                ('town_city', models.CharField(max_length=80)),
                ('county', models.CharField(max_length=80)),
                ('postcode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='income_expenditure.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IEStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('income_other', models.PositiveIntegerField()),
                ('mortgage', models.PositiveIntegerField()),
                ('rent', models.PositiveIntegerField()),
                ('utilities', models.PositiveIntegerField()),
                ('travel', models.PositiveIntegerField()),
                ('food', models.PositiveIntegerField()),
                ('loans', models.PositiveIntegerField()),
                ('credit_cards', models.PositiveIntegerField()),
                ('expenditure_other', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_expenditure.person')),
            ],
        ),
    ]
